version: "3"

services:
  php-fpm:
    build:
      context: ./php
    container_name: "php-app1"
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1

    volumes:
      - ../SuitesFlow:/var/www/
      - ../Tours:/var/www/tours
      - ./php/php.ini:/usr/local/etc/php/conf.d/99.overrides.php.ini

    networks:
      - app-network

  node-js:
    build:
      context: ../SuitesFlow-NodeJS
    container_name: "node-js"
    volumes:
      - ../SuitesFlow-NodeJS/assets/:/usr/src/app/assets/
      - ../SuitesFlow-NodeJS/components/:/usr/src/app/components/
      - ../SuitesFlow-NodeJS/common/:/usr/src/app/common/
      - ../SuitesFlow-NodeJS/layouts/:/usr/src/app/layouts/
      - ../SuitesFlow-NodeJS/middleware/:/usr/src/app/middleware/
      - ../SuitesFlow-NodeJS/mixins/:/usr/src/app/mixins/
      - ../SuitesFlow-NodeJS/pages/:/usr/src/app/pages/
      - ../SuitesFlow-NodeJS/plugins/:/usr/src/app/plugins/
      - ../SuitesFlow-NodeJS/static/:/usr/src/app/static/
      - ../SuitesFlow-NodeJS/store/:/usr/src/app/store/
      - ../SuitesFlow-NodeJS/api/:/usr/src/app/api/
      - ../SuitesFlow-NodeJS/jsconfig.json:/usr/src/app/jsconfig.json
      - ../SuitesFlow-NodeJS/nuxt.config.js:/usr/src/app/nuxt.config.js
      # - ../SuitesFlow-NodeJS/.env:/usr/src/app/.env
    working_dir: /usr/src/app/
    ports:
      - "9001:3000"
    command: sh -c "npm run dev"
    environment:
      - HOST=0.0.0.0
      - APP_API_URL=http://localhost:90
      - SSR_API_URL=http://nginx-app1
      - DATA_URL=http://localhost:90
      - SSR_DATA_URL=http://nginx-app1
      - API_SF_URL=http://nginx-app1/php/api
      - API_VT_URL=https://api.renderator.com/api
      - SSR_API_SF_URL=http://nginx-app1/php/api

      - API_DB_DATABASE=new_projects
      - API_DB_USER=new_projects_user
      - API_DB_PASSWORD=UboLEsbI819wzrxo
      - API_DB_HOST=db

      - GOOGLE_SECRET=6LfkT9AZAAAAAMFD4WXdy5Mo05FGBq8IYGihoGa5
      - GOOGLE_SITE=6LfkT9AZAAAAAB_CdVACMBP0pd61idodn7g9H0eq

    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    container_name: "nginx-app1"

    volumes:
      - ../SuitesFlow:/var/www/
      - ../Tours:/var/www/tours
      - ../Tours/renderator/action/renderatorAction.xml :/var/www/renderator/action/renderatorAction.xml
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
      - node-js

    ports:
      - "90:80"
      - "9443:443"
    networks:
      - app-network
  db:
    build:
      context: ./db
    container_name: "db-app1"
    environment:
      - MYSQL_DATABASE=render_appdb
      - MYSQL_USER=render_appdbu
      - MYSQL_PASSWORD=8BDGIegPW1
      - MYSQL_ROOT_PASSWORD=docker
    volumes:
      - ./db/data_20210104.sql:/docker-entrypoint-initdb.d/data.sql
    ports:
      - 9306:3306
    depends_on:
      - php-fpm
    networks:
      - app-network

  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "myadmin-app1"
    ports:
      - "9080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=localhost
    restart: always
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  node_modules:
  nuxt:
