#
# Ubuntu Dockerfile
#
# https://github.com/dockerfile/ubuntu
#

# Pull base image.
FROM ubuntu:14.04

# Install.
# RUN \
#   sudo apt-get install ssh \
#   sudo systemctl ssh start \
#   sudo systemctl ssh enable \
#   service ssh status

# Add files.
# ADD config/.bashrc /root/.bashrc
# ADD config/.gitconfig /root/.gitconfig
# ADD root/.scripts /root/.scripts

# Set environment variables.
# ENV HOME /root

# Define working directory.
# WORKDIR /root

# Define default command.
# CMD ["bash"]