# Image
FROM node:14.4.0

# Set up work directory
RUN mkdir -p /home/node/app && chown -R node:node /home/node/app
WORKDIR /home/node/app

USER node

# RUN npm install


EXPOSE 3000

# ENV NUXT_HOST=0.0.0.0
# ENV NUXT_PORT=3000
# Init command
# CMD ["npm", "run", "dev"]